version: "3.9"
services:
  db:
    image: "mysql:latest"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:MY-PASS
  web:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:80"
    depends_on:
      - app
  app:
    build: .
    ports:
      - "5050"
    depends_on:
      - db



volumes:
    mysql: {}